In [31]:
!pip3 install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Frameworks/Python.framework/Versions/3.14/bin/python3.14 -m pip install --upgrade pip

In [32]:
import pandas as pd
import numpy as np

In [ ]:
parking_permit_blocks = pd.read_csv(r'../data/residential_parking_permit_blocks.csv')
#N/S North Side
#S/S South Side
#E/S East Side
#W/S West Side
#B/S Both Sides

In [41]:
pd.set_option('display.max_columns', None)
parking_permit_blocks

,the_geom,the_geom_webmercator,street,city,state,latitude,longitude,district_number,block,side,lat,lng
0,0101000020E6100000F8C4FFF210C952C0D05BCD8BEAF9...,0101000020110F0000399273D1AEE85FC16CFAAE722789...,N FRONT ST,Philadelphia,PA,39.952470,-75.141659,10,99,W/S,39.952470,-75.141659
1,0101000020E610000028A7C35EF6CE52C04835024AB3FC...,0101000020110F00007CF9B7B8B2F25FC12EA6E83A3D8C...,N ITHAN ST,Philadelphia,PA,39.974221,-75.233787,3,99,W/S,39.974221,-75.233787
2,0101000020E61000006C6376C0BCCE52C0B0F135781DFA...,0101000020110F00006BC2D8D950F25FC1BD8C0ADE5F89...,PINE ST,Philadelphia,PA,39.954024,-75.230270,1,2500,B/S,39.954024,-75.230270
3,0101000020E61000009484B8303AC952C010FF113C74F8...,0101000020110F0000E0DACDDEF4E85FC1C28F48C78887...,S 13TH ST,Philadelphia,PA,39.941047,-75.144177,24,2000,B/S,39.941047,-75.144177
4,0101000020E61000006C6376C0BCCE52C0B0F135781DFA...,0101000020110F00006BC2D8D950F25FC1BD8C0ADE5F89...,PINE ST,Philadelphia,PA,39.954024,-75.230270,2,4200,S/S,39.954024,-75.230270
...,...,...,...,...,...,...,...,...,...,...,...,...
1337,0101000020E610000024C9737DFFCC52C0C05B9C7529FB...,0101000020110F00009E8970875CEF5FC1CA700FCD888A...,GREEN ST,Philadelphia,PA,39.962203,-75.203094,10,100,B/S,39.962203,-75.203094
1338,0101000020E6100000189A9B373AC952C0C0032D3E74F8...,0101000020110F000073A180EAF4E85FC18EA59DC98887...,S 15TH ST,Philadelphia,PA,39.941047,-75.144178,1,400,W/S,39.941047,-75.144178
1339,0101000020E610000018B06A6405CC52C0488E0A8F42F7...,0101000020110F0000765779B6B3ED5FC1841332323686...,BAMBREY ST,Philadelphia,PA,39.931719,-75.187829,1,600,W/S,39.931719,-75.187829
1340,0101000020E6100000B83E4B0E3AC952C0C858913174F8...,0101000020110F0000C79F53A4F4E85FC19345A6BB8887...,S 03RD ST,Philadelphia,PA,39.941046,-75.144168,5,299,E/S,39.941046,-75.144168
1341,0101000020E61000009484B8303AC952C010FF113C74F8...,0101000020110F0000E0DACDDEF4E85FC1C28F48C78887...,S 13TH ST,Philadelphia,PA,39.941047,-75.144177,23,1400,B/S,39.941047,-75.144177

In [28]:
pd.set_option('display.max_columns', None)
complete_streets = pd.read_csv(r'../data/CompleteStreets.csv')
complete_streets.head()

,OBJECTID,FNODE,TNODE,LENGTH,STCL2,STCL2_ID,PRE_DIR,ST_NAME,ST_TYPE,SEG_ID,ONEWAY,CLASS,STNAME,CLASS1,SPEEDLIM,RECSIGN,SURFAWIDTH,RECFACIL,PARKING,BIKENETWOR,LENGTH_MIL,PHASE2_SID,SIDEWALK_I,COMBINED_S,STREET_TYP,SIDEWLK_WD,WLK_ZN,Shape__Length
0,1,12545.0,23746.0,2781.749812,35640.0,5743.0,NaN,STEVENSON,ST,880652,B,5.0,STEVENSON ST,Local Residential,25,NaN,0.0,NaN,Z,NaN,0.217463,NaN,0.0,Local (Catch All),Local (Catch All),Greater than or equal to 10 feet,Greater than or equal to 5 feet,458.056119
1,2,22709.0,3314.0,1306.500445,33771.0,7071.0,NaN,FALLS,RD,621533,B,3.0,FALLS RD,Minor Arterial,30,NaN,0.0,Marked Shared Lane,Z,NaN,0.121046,Yes,5341.0,Park Road,Park Road,Greater than or equal to 8 feet,Greater than or equal to 5 feet,254.306672
2,3,21638.0,21639.0,1077.334325,31807.0,83581.0,N,66TH,ST,401204,B,3.0,N 66TH ST,Minor Arterial,30,NaN,0.0,Climbing Lane,Z,NaN,0.081224,Yes,12291.0,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,170.826679
3,4,718.0,712.0,383.723081,1025.0,85570.0,N,29TH,ST,421076,B,3.0,N 29TH ST,Minor Arterial,30,NaN,0.0,Marked Shared Lane,Z,YES,0.072675,Yes,11399.0,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,153.003351
4,5,88.0,935.0,88.455160,1393.0,8490.0,NaN,RIDGE,AVE,521274,B,3.0,RIDGE AVE,Minor Arterial,30,Yes,32.0,Marked Shared Lane,B,YES,0.016753,Yes,14295.0,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,35.253814

In [34]:
def get_valid_optins(df,column):
    print(df[column].value_counts())

In [37]:
get_valid_optins(complete_streets,'STREET_TYP')

STREET_TYP
City Neighborhood Street               13341
Local (Catch All)                      11934
Lower Density Residential               6689
Urban Arterial                          5675
Walkable Commercial Corridors            816
Auto Oriented Commercial/Industrial      552
Shared Narrow                            479
N/A Interstate                           426
Civic/Ceremonial Street                  208
Scenic Drive                             124
Park Road                                121
High Volume Pedestrian                   117
Delete                                   108
Pedestrian-Access Only                    69
Name: count, dtype: int64

In [29]:
pd.set_option('display.max_columns', 10)
complete_streets[complete_streets.STNAME.str.strip() == 'N FRONT ST']

,OBJECTID,FNODE,TNODE,LENGTH,STCL2,...,COMBINED_S,STREET_TYP,SIDEWLK_WD,WLK_ZN,Shape__Length
5402,5403,3975.0,3970.0,280.872603,6182.0,...,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,112.070905
5862,5863,3855.0,3856.0,55.956705,6003.0,...,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,22.329412
6157,6158,3970.0,3963.0,276.918400,6172.0,...,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,110.494668
6172,6173,3857.0,3858.0,53.790344,6009.0,...,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,21.463453
6365,6366,3856.0,3857.0,118.961219,6005.0,...,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,47.467414
...,...,...,...,...,...,...,...,...,...,...,...
38640,38641,14286.0,23028.0,251.225384,34296.0,...,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,100.125401
38641,38642,23028.0,14277.0,218.015996,34297.0,...,Urban Arterial,Urban Arterial,Greater than or equal to 12 feet,Greater than or equal to 6 feet,86.907843
39401,39402,25115.0,25116.0,251.867023,40267.0,...,Lower Density Residential,Lower Density Residential,Greater than or equal to 10 feet,Greater than or equal to 5 feet,100.532880
39539,39540,25116.0,20977.0,512.037165,40278.0,...,Lower Density Residential,Lower Density Residential,Greater than or equal to 10 feet,Greater than or equal to 5 feet,204.381383
39968,39969,20973.0,25115.0,542.302445,40266.0,...,City Neighborhood Street,City Neighborhood Street,Greater than or equal to 12 feet,Greater than or equal to 6 feet,216.457485

In [27]:
complete_streets.STNAME

0    STEVENSON ST
1        FALLS RD
2       N 66TH ST
3       N 29TH ST
4       RIDGE AVE
Name: STNAME, dtype: object