In [3]:
!pip3 install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

In [5]:
parking_permit_blocks = pd.read_csv(r'../data/residential_parking_permit_blocks.csv')
street_nodes = pd.read_csv(r'../data/Street_Nodes.csv')
street_centerlines = pd.read_csv(r'../data/Street_Centerline.csv')
#N/S North Side
#S/S South Side
#E/S East Side
#W/S West Side
#B/S Both Sides

In [6]:
pd.set_option('display.max_columns', None)
parking_permit_blocks
street_nodes

,X,Y,objectid,arc_,streetcl_,streetcl_i,node_id,int_id,update_,intersecti,x_coord,y_coord
0,-8.367363e+06,4.860134e+06,1,NaN,NaN,NaN,29152,29152,2006/11/02 00:00:00+00,N 16TH ST & CALLOWHILL ST,NaN,NaN
1,-8.367186e+06,4.860106e+06,2,NaN,NaN,NaN,29150,29150,2006/11/02 00:00:00+00,N 15TH ST & CALLOWHILL ST,NaN,NaN
2,-8.367152e+06,4.860318e+06,3,NaN,NaN,NaN,29148,29148,2013/02/28 00:00:00+00,N 15TH ST & HAMILTON ST,NaN,NaN
3,-8.367538e+06,4.860163e+06,4,NaN,NaN,NaN,29025,29025,2006/05/03 00:00:00+00,N 17TH ST & CALLOWHILL ST,NaN,NaN
4,-8.367547e+06,4.860104e+06,5,NaN,NaN,NaN,29021,29021,2006/05/03 00:00:00+00,N 17TH ST & CARLTON ST,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25596,-8.352965e+06,4.869284e+06,25597,NaN,NaN,NaN,30209,30209,2026/01/16 10:04:41+00,SB DELAWARE EXPY,NaN,NaN
25597,-8.364182e+06,4.874956e+06,25598,NaN,NaN,NaN,30210,30210,2026/01/16 11:16:01+00,OLD YORK RD,NaN,NaN
25598,-8.372243e+06,4.860246e+06,25599,NaN,NaN,NaN,30211,30211,2026/02/06 07:33:29+00,BUSTI ST & MANDELA WAY,NaN,NaN
25599,-8.372484e+06,4.860181e+06,25600,NaN,NaN,NaN,30212,30212,2026/02/06 08:03:29+00,N MELVILLE ST & SAINT MALACHYS WAY,NaN,NaN
25600,-8.372455e+06,4.860286e+06,25601,NaN,NaN,NaN,30213,30213,2026/02/06 08:12:04+00,N MELVILLE ST & MANDELA WAY,NaN,NaN

In [7]:
pd.set_option('display.max_columns', None)
complete_streets = pd.read_csv(r'../data/CompleteStreets.csv')
complete_streets.TNODE.max()

np.float64(25133.0)

In [8]:
full_ds = pd.merge(street_centerlines,street_nodes[['X','Y','intersecti','node_id']],left_on=['fnode_'],right_on='node_id',validate='many_to_one',how='left',suffixes=('','_from')).rename({'X':'X_from','Y':'Y_from','intersecti':'intersecti_from'},axis=1)
full_ds  = pd.merge(full_ds,street_nodes[['X','Y','intersecti','node_id']],left_on=['tnode_'],right_on='node_id',validate='many_to_one',how='left',suffixes=('','_to')).rename({'X':'X_to','Y':'Y_to','intersecti':'intersecti_to'},axis=1)

In [9]:
full_ds

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length,X_from,Y_from,intersecti_from,node_id,X_to,Y_to,intersecti_to,node_id_to
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551,-8.377195e+06,4.848714e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26705,-8.378059e+06,4.848000e+06,BARTRAM AVE,26716
1,26699,26704,NaN,NaN,935.023163,NaN,NaN,,BARTRAM,AVE,,19153,19153,9100,9198,9101.0,9199.0,16120,9100,9100,100003,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,2,371.888030,-8.376957e+06,4.849060e+06,BARTRAM AVE & DELAWARE EXPY RAMP H,26699,-8.377166e+06,4.848753e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26704
2,26704,26705,NaN,NaN,122.512608,NaN,NaN,,BARTRAM,AVE,,19153,19153,0,0,0.0,0.0,16120,0,0,100004,B,2,STATE,1998/07/09 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,3,48.720227,-8.377166e+06,4.848753e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26704,-8.377195e+06,4.848714e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26705
3,26658,26672,NaN,NaN,735.818883,NaN,NaN,,EASTWICK,PL,,19153,19153,8500,8598,8501.0,8599.0,30570,8500,8500,100006,B,5,CITY,1998/07/09 00:00:00+00,NaN,0.0,EASTWICK PL,EASTWICK PL,4,292.693856,-8.376319e+06,4.850300e+06,S 85TH ST & EASTWICK PL,26658,-8.376484e+06,4.850058e+06,S 86TH ST & EASTWICK PL,26672
4,26653,26668,NaN,NaN,735.209140,NaN,NaN,,HARLEY,PL,,19153,19153,8500,8598,8501.0,8599.0,40570,8500,8500,100007,B,5,CITY,2006/04/07 00:00:00+00,NaN,0.0,HARLEY PL,HARLEY PL,5,292.440377,-8.376399e+06,4.850357e+06,S 85TH ST & HARLEY PL,26653,-8.376567e+06,4.850118e+06,S 86TH ST & HARLEY PL,26668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41266,29254,29256,NaN,NaN,264.822078,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15132,15146,15133.0,15147.0,75477,15100,15100,1180101,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41267,105.595306,-8.347392e+06,4.883528e+06,FOXGLOVE LN & SUNFLOWER DR,29254,-8.347313e+06,4.883598e+06,IRIS LN & SUNFLOWER DR,29256
41267,29256,29259,NaN,NaN,159.663507,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15148,15152,15149.0,15153.0,75477,15100,15100,1180102,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41268,63.661475,-8.347313e+06,4.883598e+06,IRIS LN & SUNFLOWER DR,29256,-8.347265e+06,4.883640e+06,MIMOSA DR & SUNFLOWER DR,29259
41268,29259,29258,NaN,NaN,218.496317,NaN,NaN,,MIMOSA,DR,,19116,19116,2601,2699,2600.0,2698.0,56360,2600,2600,1180103,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,MIMOSA DR,MIMOSA DR,41269,87.173485,-8.347265e+06,4.883640e+06,MIMOSA DR & SUNFLOWER DR,29259,-8.347209e+06,4.883573e+06,MIMOSA DR & WILDFLOWER WAY,29258
41269,29259,29260,NaN,NaN,228.896914,NaN,NaN,,SUNFLOWER,DR,,19116,19116,15154,15198,15155.0,15199.0,75477,15100,15100,1180104,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,SUNFLOWER DR,SUNFLOWER DR,41270,91.299361,-8.347265e+06,4.883640e+06,MIMOSA DR & SUNFLOWER DR,29259,-8.347202e+06,4.883705e+06,BLUEBELL CT & SUNFLOWER DR,29260
41270,29261,29260,NaN,NaN,390.822828,NaN,NaN,,BLUEBELL,CT,,19116,19116,2601,2699,2600.0,2698.0,18050,2600,2600,1180105,B,5,CITY,2011/08/30 00:00:00+00,2008/02/28 00:00:00+00,0.0,BLUEBELL CT,BLUEBELL CT,41271,155.870463,-8.347309e+06,4.883764e+06,BLUEBELL CT & CUL DE SAC WEST,29261,-8.347202e+06,4.883705e+06,BLUEBELL CT & SUNFLOWER DR,29260

In [10]:
def get_valid_optins(df,column):
    print(df[column].value_counts())

In [11]:
get_valid_optins(complete_streets,'STREET_TYP')

STREET_TYP
City Neighborhood Street               13341
Local (Catch All)                      11934
Lower Density Residential               6689
Urban Arterial                          5675
Walkable Commercial Corridors            816
Auto Oriented Commercial/Industrial      552
Shared Narrow                            479
N/A Interstate                           426
Civic/Ceremonial Street                  208
Scenic Drive                             124
Park Road                                121
High Volume Pedestrian                   117
Delete                                   108
Pedestrian-Access Only                    69
Name: count, dtype: int64

In [12]:
from collections import defaultdict,deque
class Node: 
    def __init__(self, id,intersection):
        self.id = int(id)
        self.intersection = intersection
        
class Edge:
    def __init__(self, from_node, to_node, length, stname, oneway):
        self.from_node = from_node
        self.to_node = to_node
        self.length = length
        self.stname = stname
        self.oneway = oneway

class Graph:
    def __init__(self):
        self.nodes = {}
        self.edges = []
        self.adjacency = {}

    def get_or_create_node(self,node_id: int,intersection):
        
        if node_id not in self.nodes:
            self.nodes[node_id] = Node(node_id,intersection)
        return self.nodes[node_id]
    def add_edge(self, 
                    from_node_id,
                    from_node_intersection,
                    to_node_id,
                    to_node_intersection, 
                    length, 
                    stname, 
                    oneway):
        from_node = self.get_or_create_node(from_node_id,
                                            from_node_intersection)
        to_node = self.get_or_create_node(to_node_id,
                                          to_node_intersection)
        edge = Edge(from_node = from_node,
                        to_node =  to_node, 
                        length = length,  
                        stname = stname,
                        oneway = oneway)
        self.edges.append(edge)
    def build_adjacency(self):
        adjacency = defaultdict(list)
        for edge in self.edges:
            adjacency[edge.from_node].append(edge)
        self.adjacency=adjacency
    def show_node_adjacency(self, node_id):
        rows = []
        node = self.nodes.get(node_id,'')
        for edge in self.adjacency.get(node, []):
            rows.append({
            "from_node": edge.from_node.id,
            "to_node": edge.to_node.id,
            'from_intersection':edge.from_node.intersection,
            'to_intersection':edge.to_node.intersection,
            "street_name": edge.stname,
            "length": edge.length,
            "oneway": edge.oneway,
        })
        return pd.DataFrame(rows)
    def get_neighbors(self,start_node,max_depth =2):
        visited = {start_node}
        queue = ([(start_node,0)])
        result = []

        while queue:
            node, depth = queue.popleft()
            for node in self.adjacency.get(node,[]):
                pass

In [13]:
full_ds[(full_ds.oneway.str.strip() != '')].head(1)

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length,X_from,Y_from,intersecti_from,node_id,X_to,Y_to,intersecti_to,node_id_to
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551,-8.377195e+06,4.848714e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26705,-8.378059e+06,4.848000e+06,BARTRAM AVE,26716

In [14]:
philly_streets = Graph()

In [15]:
for ind, data in full_ds[(full_ds.oneway.str.strip() != '')].iterrows():
    fnode = data.fnode_
    tnode = data.tnode_
    length = data.length
    stname = data.stname
    oneway = data.oneway
    from_intersection = data.intersecti_from
    to_intesection = data.intersecti_to

    if oneway == 'B':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway)
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway)
    elif oneway == 'TF':
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway)
    elif oneway == 'FT':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway)

In [16]:
philly_streets.build_adjacency()

In [17]:
x = philly_streets.show_node_adjacency(3)

In [18]:
x

,from_node,to_node,from_intersection,to_intersection,street_name,length,oneway
0,3,8,COUNTY LINE RD & OVERHILL AVE,BUXMONT ST & OVERHILL AVE,OVERHILL AVE,704.031771,B
1,3,2,COUNTY LINE RD & OVERHILL AVE,COUNTY LINE RD & WEXFORD PL,COUNTY LINE RD,247.134114,B
2,3,5,COUNTY LINE RD & OVERHILL AVE,BUXMONT ST & COUNTY LINE RD,COUNTY LINE RD,535.401468,B