In [1]:
!pip3 install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /Users/kieraniphone/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip3 install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from graph import Graph,Path

In [3]:
parking_permit_blocks = pd.read_csv(r'../data/residential_parking_permit_blocks.csv')
street_nodes = pd.read_csv(r'../data/Street_Nodes.csv')
street_centerlines = pd.read_csv(r'../data/Street_Centerline.csv')
#N/S North Side
#S/S South Side
#E/S East Side
#W/S West Side
#B/S Both Sides

In [4]:
pd.set_option('display.max_columns', None)
parking_permit_blocks
street_nodes

,X,Y,objectid,arc_,streetcl_,streetcl_i,node_id,int_id,update_,intersecti,x_coord,y_coord
0,-8.367363e+06,4.860134e+06,1,NaN,NaN,NaN,29152,29152,2006/11/02 00:00:00+00,N 16TH ST & CALLOWHILL ST,NaN,NaN
1,-8.367186e+06,4.860106e+06,2,NaN,NaN,NaN,29150,29150,2006/11/02 00:00:00+00,N 15TH ST & CALLOWHILL ST,NaN,NaN
2,-8.367152e+06,4.860318e+06,3,NaN,NaN,NaN,29148,29148,2013/02/28 00:00:00+00,N 15TH ST & HAMILTON ST,NaN,NaN
3,-8.367538e+06,4.860163e+06,4,NaN,NaN,NaN,29025,29025,2006/05/03 00:00:00+00,N 17TH ST & CALLOWHILL ST,NaN,NaN
4,-8.367547e+06,4.860104e+06,5,NaN,NaN,NaN,29021,29021,2006/05/03 00:00:00+00,N 17TH ST & CARLTON ST,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25596,-8.352965e+06,4.869284e+06,25597,NaN,NaN,NaN,30209,30209,2026/01/16 10:04:41+00,SB DELAWARE EXPY,NaN,NaN
25597,-8.364182e+06,4.874956e+06,25598,NaN,NaN,NaN,30210,30210,2026/01/16 11:16:01+00,OLD YORK RD,NaN,NaN
25598,-8.372243e+06,4.860246e+06,25599,NaN,NaN,NaN,30211,30211,2026/02/06 07:33:29+00,BUSTI ST & MANDELA WAY,NaN,NaN
25599,-8.372484e+06,4.860181e+06,25600,NaN,NaN,NaN,30212,30212,2026/02/06 08:03:29+00,N MELVILLE ST & SAINT MALACHYS WAY,NaN,NaN
25600,-8.372455e+06,4.860286e+06,25601,NaN,NaN,NaN,30213,30213,2026/02/06 08:12:04+00,N MELVILLE ST & MANDELA WAY,NaN,NaN

In [5]:
pd.set_option('display.max_columns', None)
complete_streets = pd.read_csv(r'../data/CompleteStreets.csv')
complete_streets.TNODE.max()

np.float64(25133.0)

In [6]:
full_ds = pd.merge(street_centerlines,street_nodes[['X','Y','intersecti','node_id']],left_on=['fnode_'],right_on='node_id',validate='many_to_one',how='left',suffixes=('','_from')).rename({'X':'X_from','Y':'Y_from','intersecti':'intersecti_from'},axis=1)
full_ds  = pd.merge(full_ds,street_nodes[['X','Y','intersecti','node_id']],left_on=['tnode_'],right_on='node_id',validate='many_to_one',how='left',suffixes=('','_to')).rename({'X':'X_to','Y':'Y_to','intersecti':'intersecti_to'},axis=1)

In [7]:
dx = full_ds['X_to'] - full_ds['X_from']
dy = full_ds['Y_to'] - full_ds['Y_from']

full_ds['bearing'] = np.degrees(np.arctan2(dy,dx))

In [8]:
def get_valid_optins(df,column):
    print(df[column].value_counts())

In [9]:
full_ds[(full_ds.oneway.str.strip() != '')].head(1)

,fnode_,tnode_,lpoly_,rpoly_,length,stcl2_,stcl2_id,pre_dir,st_name,st_type,suf_dir,zip_left,zip_right,l_f_add,l_t_add,r_f_add,r_t_add,st_code,l_hundred,r_hundred,seg_id,oneway,class,responsibl,update_,newsegdate,multi_rep,streetlabe,stname,objectid,Shape__Length,X_from,Y_from,intersecti_from,node_id,X_to,Y_to,intersecti_to,node_id_to,bearing
0,26705,26716,NaN,NaN,2862.844615,NaN,NaN,,BARTRAM,AVE,,19153,19153,9200,9298,9201.0,9299.0,16120,9200,9200,100002,B,2,STATE,2004/05/18 00:00:00+00,NaN,0.0,BARTRAM AVE,BARTRAM AVE,1,1137.344551,-8.377195e+06,4.848714e+06,BARTRAM AVE & DELAWARE EXPY RAMP TP,26705,-8.378059e+06,4.848000e+06,BARTRAM AVE,26716,-140.45888

In [10]:
philly_streets = Graph()

In [11]:
for ind, data in full_ds[(full_ds.oneway.str.strip() != '')].iterrows():
    fnode = data.fnode_
    tnode = data.tnode_
    length = data.length
    stname = data.stname
    oneway = data.oneway
    from_intersection = data.intersecti_from
    to_intesection = data.intersecti_to
    bearing = data.bearing
    opposite = (bearing + 180) % 360
    if opposite > 180:
        opposite -= 360
    if oneway == 'B':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway,
                                bearing=bearing)
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway,
                                bearing=opposite)
    elif oneway == 'TF':
        philly_streets.add_edge(from_node_id=tnode,
                                to_node_id=fnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway,
                                bearing=opposite)
    elif oneway == 'FT':
        philly_streets.add_edge(from_node_id=fnode,
                                to_node_id=tnode,
                                from_node_intersection = from_intersection,
                                to_node_intersection = to_intesection,
                                length=length,
                                stname = stname,
                                oneway=oneway,
                                bearing=bearing)

In [12]:
philly_streets.build_adjacency()

In [13]:
x = philly_streets.show_node_adjacency(3)

In [14]:
philly_streets.adjacency

defaultdict(list,
            {<graph.Node at 0x1133286e0>: [<graph.Edge at 0x113328440>,
              <graph.Edge at 0x112debd10>,
              <graph.Edge at 0x115568ad0>],
             <graph.Node at 0x112df3610>: [<graph.Edge at 0x112df3890>,
              <graph.Edge at 0x11556b9d0>],
             <graph.Node at 0x112df3750>: [<graph.Edge at 0x112df39d0>,
              <graph.Edge at 0x1133df3d0>],
             <graph.Node at 0x112e3d810>: [<graph.Edge at 0x112e3d940>,
              <graph.Edge at 0x112e3da70>,
              <graph.Edge at 0x115568bd0>],
             <graph.Node at 0x112e3dba0>: [<graph.Edge at 0x112ea1e10>,
              <graph.Edge at 0x1133dcf50>],
             <graph.Node at 0x1133d4170>: [<graph.Edge at 0x112ea17b0>,
              <graph.Edge at 0x1133dead0>,
              <graph.Edge at 0x1133dea50>],
             <graph.Node at 0x112ea18c0>: [<graph.Edge at 0x112e90350>,
              <graph.Edge at 0x1133dce50>,
              <graph.Edge at 0x1133dcdd0>],
             <graph.Node at 0x112ea2030>: [<graph.Edge at 0x112e92c50>,
              <graph.Edge at 0x1133de9d0>,
              <graph.Edge at 0x1133de950>],
             <graph.Node at 0x1133d8250>: [<graph.Edge at 0x112e9bc50>,
              <graph.Edge at 0x1133dccd0>],
             <graph.Node at 0x1133d8150>: [<graph.Edge at 0x112e9bd40>,
              <graph.Edge at 0x1133de850>],
             <graph.Node at 0x11332da90>: [<graph.Edge at 0x112ee1b70>,
              <graph.Edge at 0x1133df750>,
              <graph.Edge at 0x115598550>],
             <graph.Node at 0x11332d9a0>: [<graph.Edge at 0x112ee2190>],
             <graph.Node at 0x112ee20b0>: [<graph.Edge at 0x1133e9300>,
              <graph.Edge at 0x112ebb330>],
             <graph.Node at 0x112ee1d30>: [<graph.Edge at 0x112ea4950>,
              <graph.Edge at 0x1133dd6d0>],
             <graph.Node at 0x1133e9230>: [<graph.Edge at 0x112ea4c50>,
              <graph.Edge at 0x1133dd150>,
              <graph.Edge at 0x1133dd0d0>],
             <graph.Node at 0x112ea4f50>: [<graph.Edge at 0x10b1b1650>,
              <graph.Edge at 0x1133dd050>,
              <graph.Edge at 0x1133dcfd0>],
             <graph.Node at 0x112ea5010>: [<graph.Edge at 0x112ed5c70>],
             <graph.Node at 0x113333490>: [<graph.Edge at 0x112ed5d10>,
              <graph.Edge at 0x115569450>,
              <graph.Edge at 0x115569950>],
             <graph.Node at 0x113333330>: [<graph.Edge at 0x112e3a570>],
             <graph.Node at 0x112ed5bd0>: [<graph.Edge at 0x112e8b650>,
              <graph.Edge at 0x1133dced0>,
              <graph.Edge at 0x115569a50>],
             <graph.Node at 0x112ed5e50>: [<graph.Edge at 0x1133dc950>],
             <graph.Node at 0x112e3a600>: [<graph.Edge at 0x1133dca50>,
              <graph.Edge at 0x1133de2d0>,
              <graph.Edge at 0x1133de250>],
             <graph.Node at 0x1133dc650>: [<graph.Edge at 0x1133dcad0>],
             <graph.Node at 0x1133dc9d0>: [<graph.Edge at 0x1133dcbd0>,
              <graph.Edge at 0x1155682d0>,
              <graph.Edge at 0x11556b1d0>],
             <graph.Node at 0x112e63cb0>: [<graph.Edge at 0x1133dcc50>,
              <graph.Edge at 0x1133dcb50>,
              <graph.Edge at 0x1133df050>,
              <graph.Edge at 0x115568850>],
             <graph.Node at 0x112e635b0>: [<graph.Edge at 0x1133dcd50>,
              <graph.Edge at 0x1133ddb50>,
              <graph.Edge at 0x1133de350>],
             <graph.Node at 0x1132ee210>: [<graph.Edge at 0x1133dd250>,
              <graph.Edge at 0x1133dd550>,
              <graph.Edge at 0x1133dec50>],
             <graph.Node at 0x1132ee330>: [<graph.Edge at 0x1133dd1d0>,
              <graph.Edge at 0x115568750>],
             <graph.Node at 0x1132ee390>: [<graph.Edge at 0x1133dd2d0>,
              <graph.Edge at 0x116001b50>],
             <graph.Node at 0x1132ec170>: [<graph.Edge at 0x1133dd3d0>,
              <graph.Edge at 0x1133dd450>,
              <graph.Edge at 0x1133ddf50>,
              <graph.Edge at 0x115569650>],
             <graph.Node at 0x1132ee450>: [<graph.Edge at 0x1133dd350>,
              <graph.Edge at 0x1155686d0>],
             <graph.Node at 0x1132ee090>: [<graph.Edge at 0x1133dd4d0>],
             <graph.Node at 0x1132ee510>: [<graph.Edge at 0x1133dd5d0>,
              <graph.Edge at 0x1133dd750>,
              <graph.Edge at 0x1133de150>],
             <graph.Node at 0x1132ef050>: [<graph.Edge at 0x1133dd650>,
              <graph.Edge at 0x11556a7d0>,
              <graph.Edge at 0x11556abd0>],
             <graph.Node at 0x1132edf10>: [<graph.Edge at 0x1133dd7d0>,
              <graph.Edge at 0x1155681d0>],
             <graph.Node at 0x1132eef30>: [<graph.Edge at 0x1133dd8d0>],
             <graph.Node at 0x1132ef110>: [<graph.Edge at 0x1133dd850>,
              <graph.Edge at 0x115568250>,
              <graph.Edge at 0x115569350>,
              <graph.Edge at 0x1155891d0>],
             <graph.Node at 0x1132ee270>: [<graph.Edge at 0x1133dd9d0>],
             <graph.Node at 0x1132ef170>: [<graph.Edge at 0x1133dd950>],
             <graph.Node at 0x1132eeff0>: [<graph.Edge at 0x1133ddad0>,
              <graph.Edge at 0x1133de6d0>,
              <graph.Edge at 0x1133de650>,
              <graph.Edge at 0x1133dfe50>],
             <graph.Node at 0x1132ef230>: [<graph.Edge at 0x1133dda50>],
             <graph.Node at 0x1132ee1b0>: [<graph.Edge at 0x1133ddbd0>,
              <graph.Edge at 0x1133de8d0>,
              <graph.Edge at 0x1133dff50>],
             <graph.Node at 0x1132ef2f0>: [<graph.Edge at 0x1133ddcd0>],
             <graph.Node at 0x1132ef3b0>: [<graph.Edge at 0x1133ddc50>],
             <graph.Node at 0x1132ef410>: [<graph.Edge at 0x1133ddd50>,
              <graph.Edge at 0x1155692d0>],
             <graph.Node at 0x1132ef4d0>: [<graph.Edge at 0x1133dddd0>,
              <graph.Edge at 0x11556aad0>,
              <graph.Edge at 0x1155765d0>],
             <graph.Node at 0x1132ecd70>: [<graph.Edge at 0x1133dded0>,
              <graph.Edge at 0x1133dde50>],
             <graph.Node at 0x1132ef590>: [<graph.Edge at 0x1133ddfd0>,
              <graph.Edge at 0x11556ae50>,
              <graph.Edge at 0x11556af50>],
             <graph.Node at 0x1132ef650>: [<graph.Edge at 0x1133de0d0>,
              <graph.Edge at 0x1133de050>,
              <graph.Edge at 0x1133df650>,
              <graph.Edge at 0x1133dfbd0>],
             <graph.Node at 0x1132ef6b0>: [<graph.Edge at 0x1133de1d0>,
              <graph.Edge at 0x1133ded50>,
              <graph.Edge at 0x115568dd0>],
             <graph.Node at 0x1132ee3f0>: [<graph.Edge at 0x1133de3d0>,
              <graph.Edge at 0x115568d50>],
             <graph.Node at 0x1132ef5f0>: [<graph.Edge at 0x1133de4d0>,
              <graph.Edge at 0x1133de450>,
              <graph.Edge at 0x1133dfd50>],
             <graph.Node at 0x1132ef530>: [<graph.Edge at 0x1133de5d0>,
              <graph.Edge at 0x1133de550>,
              <graph.Edge at 0x1133dfc50>],
             <graph.Node at 0x1132ef830>: [<graph.Edge at 0x1133de7d0>,
              <graph.Edge at 0x1133de750>,
              <graph.Edge at 0x1133df5d0>,
              <graph.Edge at 0x1133df550>],
             <graph.Node at 0x1132ef290>: [<graph.Edge at 0x1133debd0>,
              <graph.Edge at 0x1133df4d0>,
              <graph.Edge at 0x11556a350>],
             <graph.Node at 0x1132ef7d0>: [<graph.Edge at 0x1133deb50>,
              <graph.Edge at 0x115594a50>,
              <graph.Edge at 0x1155983d0>],
             <graph.Node at 0x1132ef710>: [<graph.Edge at 0x1133decd0>,
              <graph.Edge at 0x1133df2d0>,
              <graph.Edge at 0x1155696d0>],
             <graph.Node at 0x1132ef8f0>: [<graph.Edge at 0x1133dedd0>,
              <graph.Edge at 0x11556a9d0>,
              <graph.Edge at 0x115589b50>],
             <graph.Node at 0x1132ef9b0>: [<graph.Edge at 0x1133deed0>,
              <graph.Edge at 0x1133dee50>,
              <graph.Edge at 0x115568c50>],
             <graph.Node at 0x1132efa10>: [<graph.Edge at 0x1133defd0>,
              <graph.Edge at 0x1133def50>,
              <graph.Edge at 0x11559bcd0>],
             <graph.Node at 0x1132efa70>: [<graph.Edge at 0x1133df0d0>,
              <graph.Edge at 0x1155680d0>,
              <graph.Edge at 0x11558b8d0>],
             <graph.Node at 0x1132ee0f0>: [<graph.Edge at 0x1133df150>],
             <graph.Node at 0x1132ef950>: [<graph.Edge at 0x1133df1d0>],
             <graph.Node at 0x1132ee2d0>: [<graph.Edge at 0x1133df250>,
              <graph.Edge at 0x11556a050>,
              <graph.Edge at 0x11556a3d0>],
             <graph.Node at 0x1132efb90>: [<graph.Edge at 0x1133df350>,
              <graph.Edge at 0x115568350>,
              <graph.Edge at 0x11556ab50>],
             <graph.Node at 0x1132efbf0>: [<graph.Edge at 0x1133df450>,
              <graph.Edge at 0x115568950>],
             <graph.Node at 0x1132efc50>: [<graph.Edge at 0x1133df6d0>],
             <graph.Node at 0x1132efcb0>: [<graph.Edge at 0x1133df7d0>],
             <graph.Node at 0x1132efd10>: [<graph.Edge at 0x1133df8d0>,
              <graph.Edge at 0x115569850>,
              <graph.Edge at 0x1155697d0>,
              <graph.Edge at 0x1155698d0>],
             <graph.Node at 0x1132efd70>: [<graph.Edge at 0x1133df850>,
              <graph.Edge at 0x115568650>],
             <graph.Node at 0x1132efb30>: [<graph.Edge at 0x1133df9d0>],
             <graph.Node at 0x1132efdd0>: [<graph.Edge at 0x1133df950>,
              <graph.Edge at 0x1155687d0>],
             <graph.Node at 0x1132ef890>: [<graph.Edge at 0x1133dfad0>],
             <graph.Node at 0x1132efe90>: [<graph.Edge at 0x1133dfa50>,
              <graph.Edge at 0x115569550>],
             <graph.Node at 0x1132eff50>: [<graph.Edge at 0x1133dfb50>,
              <graph.Edge at 0x1155688d0>],
             <graph.Node at 0x1132ef350>: [<graph.Edge at 0x1133dfcd0>],
             <graph.Node at 0x1132effb0>: [<graph.Edge at 0x1133dfdd0>],
             <graph.Node at 0x1132efef0>: [<graph.Edge at 0x1133dfed0>],
             <graph.Node at 0x1132ee4b0>: [<graph.Edge at 0x115568050>],
             <graph.Node at 0x1132efe30>: [<graph.Edge at 0x115568150>],
             <graph.Node at 0x1132efad0>: [<graph.Edge at 0x1155683d0>,
              <graph.Edge at 0x115605a50>,
              <graph.Edge at 0x1156286d0>,
              <graph.Edge at 0x1156287d0>],
             <graph.Node at 0x1132ef770>: [<graph.Edge at 0x1155684d0>,
              <graph.Edge at 0x1156054d0>,
              <graph.Edge at 0x115627350>,
              <graph.Edge at 0x1156275d0>],
             <graph.Node at 0x1132ee150>: [<graph.Edge at 0x115568450>],
             <graph.Node at 0x1132ef0b0>: [<graph.Edge at 0x115568550>],
             <graph.Node at 0x1132ef470>: [<graph.Edge at 0x1155685d0>,
              <graph.Edge at 0x115569250>],
             <graph.Node at 0x11556c1d0>: [<graph.Edge at 0x1155689d0>,
              <graph.Edge at 0x115569bd0>],
             <graph.Node at 0x1132eef90>: [<graph.Edge at 0x115568a50>],
             <graph.Node at 0x11556c170>: [<graph.Edge at 0x115568b50>,
              <graph.Edge at 0x115569050>],
             <graph.Node at 0x11556c650>: [<graph.Edge at 0x115568cd0>],
             <graph.Node at 0x11556c6b0>: [<graph.Edge at 0x115568e50>],
             <graph.Node at 0x11556c710>: [<graph.Edge at 0x115568ed0>],
             <graph.Node at 0x11556c2f0>: [<graph.Edge at 0x115568f50>],
             <graph.Node at 0x11556c7d0>: [<graph.Edge at 0x115568fd0>,
              <graph.Edge at 0x11606abd0>,
              <graph.Edge at 0x11606ac50>],
             <graph.Node at 0x11556c890>: [<graph.Edge at 0x1155690d0>,
              <graph.Edge at 0x11556b550>],
             <graph.Node at 0x11556c4d0>: [<graph.Edge at 0x115569150>],
             <graph.Node at 0x11556c590>: [<graph.Edge at 0x1155691d0>],
             <graph.Node at 0x11556c950>: [<graph.Edge at 0x1155693d0>],
             <graph.Node at 0x11556c9b0>: [<graph.Edge at 0x1155694d0>,
              <graph.Edge at 0x115569750>],
             <graph.Node at 0x11556ca10>: [<graph.Edge at 0x1155695d0>],
             <graph.Node at 0x11556c470>: [<graph.Edge at 0x1155699d0>],
             <graph.Node at 0x11556c770>: [<graph.Edge at 0x115569b50>,
              <graph.Edge at 0x11556b050>],
             <graph.Node at 0x11556c410>: [<graph.Edge at 0x115569ad0>],
             <graph.Node at 0x11556cb90>: [<graph.Edge at 0x115569cd0>],
             <graph.Node at 0x11556cbf0>: [<graph.Edge at 0x115569c50>,
              <graph.Edge at 0x115569fd0>,
              <graph.Edge at 0x11556afd0>],
             <graph.Node at 0x11556c8f0>: [<graph.Edge at 0x115569dd0>,
              <graph.Edge at 0x115569d50>,
              <graph.Edge at 0x11556a0d0>],
             <graph.Node at 0x11556cc50>: [<graph.Edge at 0x115569ed0>,
              <graph.Edge at 0x11556a1d0>],
             <graph.Node at 0x11556cd10>: [<graph.Edge at 0x115569e50>,
              <graph.Edge at 0x11556a150>,
              <graph.Edge at 0x11556b0d0>],
             <graph.Node at 0x11556cd70>: [<graph.Edge at 0x115569f50>,
              <graph.Edge at 0x11556a2d0>,
              <graph.Edge at 0x11556a250>],
             <graph.Node at 0x11556cb30>: [<graph.Edge at 0x11556a4d0>],
             <graph.Node at 0x11556c290>: [<graph.Edge at 0x11556a450>,
              <graph.Edge at 0x11556a550>],
             <graph.Node at 0x11556cef0>: [<graph.Edge at 0x11556a5d0>,
              <graph.Edge at 0x11556a650>,
              <graph.Edge at 0x11556a6d0>],
             <graph.Node at 0x11556ce90>: [<graph.Edge at 0x11556a750>],
             <graph.Node at 0x11556cdd0>: [<graph.Edge at 0x11556a850>,
              <graph.Edge at 0x11606a250>],
             <graph.Node at 0x11556c110>: [<graph.Edge at 0x11556a950>,
              <graph.Edge at 0x11556a8d0>],
             <graph.Node at 0x11556ce30>: [<graph.Edge at 0x11556aa50>,
              <graph.Edge at 0x11606a3d0>],
             <graph.Node at 0x11556ccb0>: [<graph.Edge at 0x11556ac50>],
             <graph.Node at 0x11556c050>: [<graph.Edge at 0x11556ad50>,
              <graph.Edge at 0x11556b250>],
             <graph.Node at 0x11556c3b0>: [<graph.Edge at 0x11556acd0>],
             <graph.Node at 0x11556d190>: [<graph.Edge at 0x11556add0>,
              <graph.Edge at 0x1155aa1d0>],
             <graph.Node at 0x11556cf50>: [<graph.Edge at 0x11556aed0>,
              <graph.Edge at 0x11556be50>,
              <graph.Edge at 0x1155bac50>],
             <graph.Node at 0x11556c830>: [<graph.Edge at 0x11556b150>,
              <graph.Edge at 0x115576350>],
             <graph.Node at 0x11556cfb0>: [<graph.Edge at 0x11556b2d0>,
              <graph.Edge at 0x11556b350>],
             <graph.Node at 0x11556d370>: [<graph.Edge at 0x11556b3d0>,
              <graph.Edge at 0x11556b450>],
             <graph.Node at 0x11556d430>: [<graph.Edge at 0x11556b4d0>,
              <graph.Edge at 0x11556b5d0>],
             <graph.Node at 0x11556d0d0>: [<graph.Edge at 0x11556b650>],
             <graph.Node at 0x11556d1f0>: [<graph.Edge at 0x11556b750>,
              <graph.Edge at 0x1160693d0>,
              <graph.Edge at 0x116069450>],
             <graph.Node at 0x11556d250>: [<graph.Edge at 0x11556b6d0>,
              <graph.Edge at 0x11556b7d0>],
             <graph.Node at 0x11556d670>: [<graph.Edge at 0x11556b850>,
              <graph.Edge at 0x11606a350>],
             <graph.Node at 0x11556d070>: [<graph.Edge at 0x11556b8d0>],
             <graph.Node at 0x11556d6d0>: [<graph.Edge at 0x11556b950>,
              <graph.Edge at 0x11556bb50>],
             <graph.Node at 0x11556d4f0>: [<graph.Edge at 0x11556ba50>,
              <graph.Edge at 0x115576dd0>,
              <graph.Edge at 0x115576d50>],
             <graph.Node at 0x11556d790>: [<graph.Edge at 0x11556bad0>],
             <graph.Node at 0x11556d730>: [<graph.Edge at 0x11556bbd0>,
              <graph.Edge at 0x115576ed0>],
             <graph.Node at 0x11556d3d0>: [<graph.Edge at 0x11556bc50>],
             <graph.Node at 0x11556d8b0>: [<graph.Edge at 0x11556bcd0>,
              <graph.Edge at 0x11556bed0>,
              <graph.Edge at 0x115574d50>],
             <graph.Node at 0x11556d610>: [<graph.Edge at 0x11556bdd0>,
              <graph.Edge at 0x115574dd0>,
              <graph.Edge at 0x115576150>,
              <graph.Edge at 0x115576550>],
             <graph.Node at 0x11556d850>: [<graph.Edge at 0x11556bd50>],
             <graph.Node at 0x11556d970>: [<graph.Edge at 0x115574050>,
              <graph.Edge at 0x11556bf50>,
              <graph.Edge at 0x1155754d0>],
             <graph.Node at 0x1132ef1d0>: [<graph.Edge at 0x115574150>,
              <graph.Edge at 0x115575950>,
              <graph.Edge at 0x1155760d0>,
              <graph.Edge at 0x1155764d0>],
             <graph.Node at 0x11556da30>: [<graph.Edge at 0x1155740d0>,
              <graph.Edge at 0x115575250>],
             <graph.Node at 0x11556d910>: [<graph.Edge at 0x1155741d0>,
              <graph.Edge at 0x1155756d0>],
             <graph.Node at 0x11556daf0>: [<graph.Edge at 0x115574250>,
              <graph.Edge at 0x1155762d0>],
             <graph.Node at 0x11556dbb0>: [<graph.Edge at 0x1155742d0>,
              <graph.Edge at 0x1155747d0>],
             <graph.Node at 0x11556dc70>: [<graph.Edge at 0x115574350>],
             <graph.Node at 0x11556da90>: [<graph.Edge at 0x115574450>,
              <graph.Edge at 0x115575450>,
              <graph.Edge at 0x115575750>],
             <graph.Node at 0x11556dcd0>: [<graph.Edge at 0x1155743d0>,
              <graph.Edge at 0x115574650>,
              <graph.Edge at 0x115575350>],
             <graph.Node at 0x11556d9d0>: [<graph.Edge at 0x115574550>,
              <graph.Edge at 0x115574cd0>],
             <graph.Node at 0x11556dd90>: [<graph.Edge at 0x1155744d0>],
             <graph.Node at 0x11556de50>: [<graph.Edge at 0x1155745d0>,
              <graph.Edge at 0x115575150>,
              <graph.Edge at 0x1155dfdd0>],
             <graph.Node at 0x11556deb0>: [<graph.Edge at 0x1155746d0>,
              <graph.Edge at 0x115576450>],
             <graph.Node at 0x11556d550>: [<graph.Edge at 0x115574750>],
             <graph.Node at 0x11556d5b0>: [<graph.Edge at 0x115574850>,
              <graph.Edge at 0x115575bd0>],
             <graph.Node at 0x11556c530>: [<graph.Edge at 0x1155748d0>],
             <graph.Node at 0x11556e030>: [<graph.Edge at 0x115574950>,
              <graph.Edge at 0x11559b950>,
              <graph.Edge at 0x115620dd0>],
             <graph.Node at 0x11556df10>: [<graph.Edge at 0x115574a50>,
              <graph.Edge at 0x115576a50>,
              <graph.Edge at 0x115577950>,
              <graph.Edge at 0x11559a850>],
             <graph.Node at 0x11556d010>: [<graph.Edge at 0x1155749d0>,
              <graph.Edge at 0x115574ad0>],
             <graph.Node at 0x11556e0f0>: [<graph.Edge at 0x115574b50>,
              <graph.Edge at 0x1155d5ad0>],
             <graph.Node at 0x11556df70>: [<graph.Edge at 0x115574bd0>],
             <graph.Node at 0x11556d7f0>: [<graph.Edge at 0x115574c50>],
             <graph.Node at 0x11556dd30>: [<graph.Edge at 0x115574e50>,
              <graph.Edge at 0x115575650>,
              <graph.Edge at 0x115575e50>],
             <graph.Node at 0x11556e270>: [<graph.Edge at 0x115574f50>,
              <graph.Edge at 0x1155757d0>],
             <graph.Node at 0x11556e2d0>: [<graph.Edge at 0x115574ed0>,
              <graph.Edge at 0x1155a0150>],
             <graph.Node at 0x11556e330>: [<graph.Edge at 0x115574fd0>,
              <graph.Edge at 0x115575850>],
             <graph.Node at 0x11556e150>: [<graph.Edge at 0x115575050>],
             <graph.Node at 0x11556db50>: [<graph.Edge at 0x1155750d0>,
              <graph.Edge at 0x115575550>,
              <graph.Edge at 0x115575b50>],

In [15]:
path = Path(x.from_node_obj[0])
print(path)
path.drive_edge(x.edge[0])
print(path)

COUNTY LINE RD & OVERHILL AVE
COUNTY LINE RD & OVERHILL AVE -> OVERHILL AVE -> BUXMONT ST & OVERHILL AVE

In [20]:
x

Empty DataFrame
Columns: []
Index: []